### ISSUE TITLE
Fatal: get_marker is gone as of pytest 4.0

### ISSUE THREAD

**Issue by RockHoward** [miketheman/pytest-socket#16]
All my tests started failing when pytest 4.1.0 was released.

**Comment by miketheman** [comment]
Thanks for reporting! Will check out soon.

**Comment by Lauriy** [comment]
We also noticed. Thanks for the fix. Release soon?

**Comment by miketheman** [comment]
Released in 0.3.2 https://pypi.org/project/pytest-socket/0.3.2/
