### ISSUE TITLE
Question about asynctest and Python 3.8+ compatibility

### ISSUE THREAD

**Issue by Hellseher** [miketheman/pytest-socket#161]
Hi,

While packing your project for Guix I've faced with issue of abandoned `Martiusweb/asynctest` project wich you use in https://github.com/miketheman/pytest-socket/blob/57c905e745b13dfcc82007132d0e76f89b7fd77e/tests/test_async.py#L10 but the project itself lost support for Python 3.8+.

- https://github.com/Martiusweb/asynctest/issues/160
- https://github.com/Martiusweb/asynctest/issues/158

May you provide any details on further requirements for `Martiusweb/asynctest` in your test suit?

Thanks.

**Comment by miketheman** [comment]
Thanks for the report!

Usage of asynctest is only in a single usage you referenced, to execute a test suite that uses the asynctest library, reported back in #6 

If the library is no longer active, I would be happy to review a pull request to remove it, but ot does still appear to work: https://github.com/miketheman/pytest-socket/actions/runs/3101558257/jobs/5343958310#step:5:51

**Comment by miketheman** [comment]
asynctest completely fails in Python 3.11 - see https://github.com/miketheman/pytest-socket/pull/175

Going to need to resolve this somehow.
