### ISSUE TITLE
Allow host masks

### ISSUE THREAD

**Issue by mgaitan** [miketheman/pytest-socket#180]
I'm wondering if we could allow a range of IP as a mask. This is covered by the builtin [ipaddress](module. 

consider this example 

```
In [8]: from ipaddress import ip_network, ip_address

In [9]: ip_address('178.18.0.23') in ip_network('178.18.0.0/24')
Out[9]: True

In [10]: ip_address('178.18.0.1') in ip_network('178.18.0.0/24')
Out[10]: True

In [11]: ip_address('178.18.0.255') in ip_network('178.18.0.0/24')
Out[11]: True

In [12]: ip_address('178.18.1.1') in ip_network('178.18.0.0/24')
Out[12]: False
```

that check could complement this line

https://github.com/miketheman/pytest-socket/blob/edb216c6221c7771a8892b6653b3c96d374d1a55/pytest_socket.py#L182

I could send a PR if you are interested.

**Comment by miketheman** [comment]
@mgaitan Thanks for the interest! Someone started this effort in #73 - did you look at that already?

**Comment by mgaitan** [comment]
No, sorry! I will check that and try to help there.
