### ISSUE TITLE
Allow private networks only

### ISSUE THREAD

**Issue by nefrob** [miketheman/pytest-socket#211]
Not sure if feature request or documentation clarification if the feature already exists.

It would be nice to allow local network ip addresses to succeed and reject public networks, i.e. `ip_address(ip).is_private is True`.  This is useful when tests make requests to other docker containers on the local network with variable ip addresses but we still do not want requests going to the outside world.

Any clarification or follow up would be great thanks!

**Comment by miketheman** [comment]
@nefrob I like this idea, but am not certain on how a user would interact with the library to set this - can you suggest how you'd expect to set this configuration?

**Comment by nefrob** [comment]
@miketheman I was thinking as a pytest option like `pytest --disable-socket --allow-all-private-hosts` or via marker `@pytest.mark.allow_all_private_hosts` like is already being done. 

Right now I'm not using this package rather a simple fixture setup like the below but would be able to switch if this was supported.


```python
_original_connect = socket.socket.connect

@pytest.fixture(autouse=True)
def disable_network():
    socket.socket.connect = patched_connect
    yield
    socket.socket.connect = _original_connect

def patched_connect(*args, **kwargs):
    address = args[1]

    if isinstance(address, str):
        # AF_UNIX
        ip = address
    elif len(address) == 2:
        # AF_INET
        ip, port = address
    else:
        # AF_INET6
        ip, port, _, _ = address

    if ip_address(ip).is_private:
        return _original_connect(*args, **kwargs)

    pytest.fail("Public network request detected")
```

Not sure if this is within the desired use cases of this repo.

**Comment by dfop02** [comment]
> @miketheman I was thinking as a pytest option like `pytest --disable-socket --allow-all-private-hosts` or via marker `@pytest.mark.allow_all_private_hosts` like is already being done.
> 
> Right now I'm not using this package rather a simple fixture setup like the below but would be able to switch if this was supported.
> 
> ```python
> import socket
> from ipaddress import ip_address
> 
> import pytest
> 
> _original_connect = socket.socket.connect
> 
> @pytest.fixture(autouse=True)
> def disable_network():
>     socket.socket.connect = patched_connect
>     yield
>     socket.socket.connect = _original_connect
> 
> def patched_connect(*args, **kwargs):
>     address = args[1]
> 
>     if isinstance(address, str):
>         # AF_UNIX
>         ip = address
>     elif len(address) == 2:
>         # AF_INET
>         ip, port = address
>     else:
>         # AF_INET6
>         ip, port, _, _ = address
> 
>     if ip_address(ip).is_private:
>         return _original_connect(*args, **kwargs)
> 
>     pytest.fail("Public network request detected")
> ```
> 
> Not sure if this is within the desired use cases of this repo.

Your solution worked like a charm, thx, hope they can add on plugin too soon
