### ISSUE TITLE
Python 2.7/3.4 Support

### ISSUE THREAD

**Issue by miketheman** [miketheman/pytest-socket#23]
Following #21 and associated fix in #22 to accommodate a Python 2.7 behavior, I started thinking about when this plugin should stop supporting Python 2.7 / 3.4

According to the https://pythonclock.org/ , support ends at the end of 2019.

pytest has started warning about deprecation:
```
You are using Python 2.7.15, which will no longer be supported in pytest 5.0
```
pytest 5.0 is [scheduled for sometime mid-2019](https://docs.pytest.org/en/latest/py27-py34-deprecation.html) - after which the pytest 4.x branch will continue to be supported until mid-2020.

Please use this issue to discuss your use cases and expectations for longer-term support if you're looking for those versions to be supported beyond the runtime and test framework's lifetime.

**Comment by miketheman** [comment]
Today I learned of this nice visual representation of the lifecycle: https://python-release-cycle.glitch.me/
So I think it's safe to consider that support for 2.7 and 3.4 can be removed at the end of 2019.

**Comment by atugushev** [comment]
The `3.4` has been dropped by many projects since April. The `2.7` better to drop 01.01.2020.

**Comment by miketheman** [comment]
Today I noticed that Python 3.4 no longer works with `pip` version 20.x and fails the Appveyor build.

Things I'm going to consider:

- Migrate from TravisCI & AppVeyor to GitHub Actions for Linux, Windows, and add Mac
- Remove tox from the equation and use the base `pytest` command
- Drop support for Python 2.7, 3.4 (3.4 hit [EOL over a year ago](https://www.python.org/downloads/release/python-3410/))
- Add test support for Python 3.8, maybe 3.9, maybe pypy (See #20 )
- Convert project to use [`poetry`](https://python-poetry.org/) for build/release tooling - no impact to end users

After a few of these things are done, I'll close out this issue, and get back to triage/testing the rest of the open issues.
