### ISSUE TITLE
Automatic skips for tests using sockets

### ISSUE THREAD

**Issue by jayvdb** [miketheman/pytest-socket#25]
It would be useful to be able to automatically skip tests which used sockets, instead of failing them.

See https://github.com/venmo/nose-detecthttp/issues/9 for a more complete explanation of the use case.

**Comment by jayvdb** [comment]
Turns out that this wont be especially helpful for my use-case unless it also intercepts name resolution, as that fails first, before sockets are opened.

**Comment by jayvdb** [comment]
For name resolution, it should be relatively easy to wrap/block `socket.getaddrinfo` by overwriting it with a new function/class which achieves this.

And it looks like https://github.com/disqus/nose-socket-whitelist might do the trick

**Comment by miketheman** [comment]
That's an interesting approach, would you consider how this might apply as a config argument that makes sense to a user?

**Comment by jayvdb** [comment]
OK, well this plugin claims to be blocking `socket`, but it isnt blocking `socket.getaddrinfo` , and possibly a few other bits which could be useful.

This extra socket blocking could be exposed to the user either as

- extra granularity, e.g. --disable-socket=socket,socket.connect,getaddrinfo,getfqdn,sethostname,etc , or
- extra layers, e.g. --disable-name-lookup

**Comment by miketheman** [comment]
I've thought more about this, and from a testing behavior, I'd prefer my test suite to fail if someone added a usage of a socket that wasn't expected, as then the test suite would pass providing a false sense of security.

I'll leave the issue open and tagged with "help wanted" if anyone wanted to work on this as an opt-in feature.

**Comment by jayvdb** [comment]
I had envisioned this only as an opt-in.
