### ISSUE TITLE
Feature request: Pass in custom exception

### ISSUE THREAD

**Issue by Midnighter** [miketheman/pytest-socket#30]
Hi,

First off, this looks like a super useful plugin. Clear use-case and implementation. I lack one feature, though, I have a function that has different outcomes based on an internet connection being available. Thus it runs different code based on a `requests.exceptions.ConnectionError`. I have now replicated your logic in my code but I was wondering whether you can see enabling passing down the exception class and message as a feature?

**Comment by Midnighter** [comment]
You did a bad job :slightly_frowning_face:

**Comment by miketheman** [comment]
Hi @Midnighter !

Thanks for suggesting this (sorry about the bot - it's just a bot, you know?).

Can you provide some more context on your use case? Would this be a case where you're providing an explicit allow, but want to catch the behavior?

A snippet of the function logic would help, as well as the kind of test case you're looking to evaluate.

**Comment by Midnighter** [comment]
Hey,

> sorry about the bot - it's just a bot, you know?

No worries :slightly_smiling_face: just wanted to provide feedback for the bot creator.

So what I'm after is to test all the different branch points of a `try`/`except`, for example,

```py
try:
    # make API call
except ConnectionError:
    # handle this case
```

So my current test setup code for this looks like:

```py
import socket

import pytest
from requests import ConnectionError


_original_socket = socket.socket


def interrupt(*args, **kwargs):
    raise ConnectionError()


@pytest.fixture(scope="function")
def disconnect():
    socket.socket = interrupt
    yield
    socket.socket = _original_socket
```

Since different libraries all have their own exceptions, it'd be neat to pass the type of the exception to be raised into pytest-socket. Maybe I have misunderstood something fundamental, though.

**Comment by miketheman** [comment]
Thanks for providing the example, but I think I'm not entirely sure on how this works with this plugin.
If the code being tested is going to catch specific errors, maybe mocking out the underlying call with the specific error class is more relevant? This plugin is more useful for blocking wide-range network calls.

**Comment by Midnighter** [comment]
Yes, you are right that mocking is a good option for this case.
