### ISSUE TITLE
Add similar mock

### ISSUE THREAD

**Issue by RoelantStegmann** [miketheman/pytest-socket#325]
I like this package, but now I need to only disable internet in part of my test - this way I can test if a certain caching method indeed prevents requests to pages, and thus will work when connection fails. I don't find in the docs if this is supported?
```
def some_test():
    # This runs with internet
    ...

    # This runs without 
    with no_internet:
         .... 

    # This should run with 
    ...
```

**Comment by miketheman** [comment]
While we don't yet have the exact behavior you're describing (using the `with` context manager), you can likely accomplish this by calling the disable/enable functions directly.

Here's an example:

```python
from pytest_socket import disable_socket, enable_socket

...

def test_something()
    # This runs with internet
	...

    disable_socket()
    # This runs without
    ...
    enable_socket()

    # This should run with 
    ...
```

If you'd like to submit a patch with tests that implements the context manager protocol that does this, that'd be great!
