### ISSUE TITLE
setting allow-hosts through environment variables

### ISSUE THREAD

**Issue by deronnax** [miketheman/pytest-socket#356]
Hello @miketheman.
For our usage, we would like to set at invoke time the allowed host through environment variables, to allow access to docker-compose's redis and postgres.
Would that something you would be willing to integrate in pytest-socket?
Cheers.

**Comment by miketheman** [comment]
Hi @deronnax ,
Thanks for reaching out.

I think there's already a non trivial amount of configuration in play, and I'm not certain it's worth the added complexity.

I am not super familiar with other pytest plugins taking configuration outside of the "normal" pytest approach of 'addopts'.

Do you not have the ability to dynamically set the pytest execution command in your desired environment?

**Comment by deronnax** [comment]
Thank you for your answer. We will do without it then.
