### ISSUE TITLE
Scopes "module" or "class" circumvent the blocking

### ISSUE THREAD

**Issue by ymyke** [miketheman/pytest-socket#45]
Thanks for the great plugin!

I noticed the following:

**Example 1:**

```python
import requests

def test():
    requests.get("http://httpbin.org/status/200")
```

This will raise `SocketBlockedError`, as expected.

**Example 2:**

```python
import pytest
import requests

@pytest.fixture # scope == "function" by default
def getit():
    requests.get("http://httpbin.org/status/200")

def test(getit):
    pass
```

This will also raise the `SocketBlockedError`. Also as expected.

**Example 3:**

```python
import pytest
import requests

@pytest.fixture(scope="module") # <== Notice the different scope!
def getit():
    requests.get("http://httpbin.org/status/200")

def test(getit):
    pass
```

This will pass. No exception.

To me, this was unexpected and lead to some debugging headaches. 

Is this intended behavior or a bug? Is there a way to make the plugin also prevent cases such as this one?

**Comment by ymyke** [comment]
Looking into the pytest socket code and the pytest documentation, this seems to be expected behavior: 

* `socket_disabled` is a normal fixture, i.e. with "function" scope.
* [Fixture resolution order](https://docs.pytest.org/en/stable/fixture.html#order-higher-scoped-fixtures-are-instantiated-first) states that higher order fixtures are resolved before lower order ones.

Hence, in example 3 above the `get` call will happen before the `socket_disabled` fixture.

Maybe worth mentioning this in the documentation.

**Comment by miketheman** [comment]
Hi @ymyke !
Thanks for the diagnosis, and report.

Where in the documentation would you have expected to find this kind of specific behavior definition?

**Comment by ymyke** [comment]
Maybe in a separate section called "Caveats" or "Gotchas"? Or in an FAQ section? Maybe with a title such as "Network access in some of my fixtures work despite disabling sockets, why?".

**Comment by miketheman** [comment]
@ymyke Please check out https://github.com/miketheman/pytest-socket/pull/61 and let me know what you think!
