### ISSUE TITLE
Ability to block by socket number ?

### ISSUE THREAD

**Issue by stuaxo** [miketheman/pytest-socket#49]
Hi,
   Is it possible to extend this so it can enable/disable by socket number(s) ?

(And if not, then this is a feature request, for the same)

Cheers

**Comment by sprine** [comment]
From the [README](https://github.com/miketheman/pytest-socket/blob/master/README.rst):

```
@pytest.mark.allow_hosts(['127.0.0.1'])
def test_explicitly_enable_socket_with_mark():
    assert socket.socket.connect(('127.0.0.1', 80))
```
