### ISSUE TITLE
socket_enabled does not completely enable socket

### ISSUE THREAD

**Issue by fj-dt** [miketheman/pytest-socket#57]
When I do:

```python
import requests
from pytest import fixture


@fixture
def my_fixture():
    requests.get("https://google.com")


def test_abc(my_fixture, socket_enabled):
    assert True
```

I expect `socket_enabled` to completely enable calls to socket. However, this currently fails in the fixture.

Same if I do:

```python
def r():
    requests.get("https://google.com")
    return True


def test_def(socket_enabled):
    assert r()
```

And same if I use `@pytest.mark.enable_socket`.

My setup.cfg:

```
[tool:pytest]
addopts = --allow-hosts=127.0.0.1
```

**Comment by miketheman** [comment]
Thanks - this looks very similar to #45 - had you seen that one?

**Comment by fj-dt** [comment]
Hello Mike.
I had a look at this issue and the fixed you've made in the documentation.
In my opinion it still seems weird to me that this one does not work:

```python
def r():
    requests.get("https://google.com")
    return True


def test_def(socket_enabled):
    assert r()
```

`test_def` is testing function `r()`, this function is calling google.com. Since I used `socket_enabled` in my test, this should allow the function to call google.com.

**Comment by miketheman** [comment]
Hey @fj-dt ! I've ran through these examples on the latest code on `main`, and the plugin now behaves as you'd expect.
I'll be releasing 0.50.0 soon, but if you wanted to verify, you could use the current main branch.

Closing - if it doesn't work out, please reopen!
