### ISSUE TITLE
Include tests in PyPI tarball

### ISSUE THREAD

**Issue by kwshi** [miketheman/pytest-socket#68]
Currently, the PyPI source archive does not contain the tests for `pytest-socket`:
```
> curl -fsSL 'https://files.pythonhosted.org/packages/source/p/pytest-socket/pytest-socket-0.4.0.tar.gz' | tar -tz
pytest-socket-0.4.0/LICENSE
pytest-socket-0.4.0/README.md
pytest-socket-0.4.0/pyproject.toml
pytest-socket-0.4.0/pytest_socket.py
pytest-socket-0.4.0/setup.py
pytest-socket-0.4.0/PKG-INFO
```

OS/distribution package vendors rely on package tests to validate sanity/functionality of packages; as such, it would be a good idea to ship these tests together with the rest of the source.  It can be done by adding the following line to `pyproject.toml` (documentation [here](https://python-poetry.org/docs/pyproject/#packages)):

```
include = [{ path = "tests", format = "sdist" }]
```

**Comment by miketheman** [comment]
@kwshi Thank you for raising this!

I appreciate the position package vendors have in this regard.

Reading more about this inclusion, I don't understand how the source distribution will know which test dependencies to install, as I do not see hat key in the generated setup.py file.

[These dependencies](https://github.com/miketheman/pytest-socket/blob/0041f87faa07a973553140f0711ad2eb2e564bde/pyproject.toml#L33-L39) are necessary for the project to run tests, how does the package vendor get notified of them?

**Comment by kwshi** [comment]
@miketheman Great question--there's two parts to this answer:
- How to get poetry to add a `tests_require` key in the generated `setup.py`?  I did some digging, and I could not figure out an answer--for some reason, nobody else has asked this question, and the current version of Poetry doesn't seem to have this feature documented anywhere, even if it has it.  There was https://github.com/python-poetry/poetry/issues/1644 raised on the Poetry repository, in response to which "dependency groups" were recently implemented in the (unstable) development branch of Poetry (see also https://github.com/python-poetry/poetry/issues/1856#issue-547696549) and documented [here](https://python-poetry.org/docs/master/managing-dependencies/#dependency-groups), but this feature is not released yet, and it's unclear as to whether Poetry itself will actually make use of this feature in its `setup.py` generation step.
- OS vendors _specifically_ know about test dependencies because they are all manually specified upon being added to the package repository (as such, packages generally require _manual_ attention from maintainers in the sense of manually checking upstream for updates, making sure dependencies are correct, etc.)  As an example, you can see the line that specifies the test dependencies for `python3-wheel` in the `void-packages` repository here: https://github.com/void-linux/void-packages/blob/5f0ed9f35fbbf2313205b2fc942942c870739e04/srcpkgs/python3-wheel/template#L9.  So from the vendor perspective it's not essential for `setup.py` to actually specify test dependencies (since they are manually recorded); only for the sdist bundle to include the test files so it can run them.

**Comment by miketheman** [comment]
@kwshi Excellent response, thanks! I'll be happy to incorporate this change soon and release a patch version package.
