### ISSUE TITLE
Docker SDK unix socket connections blocked

### ISSUE THREAD

**Issue by ryanjdillon** [miketheman/pytest-socket#78]
I am using the Docker python SDK, and I get the following error when connections to `127.0.0.1` are allowed, and also passing `--allow-unix-socket`.

> E           docker.errors.DockerException: Error while fetching server API version: A test tried to > use socket.socket.connect() with host "None" (allowed: "127.0.0.1").

I'm using the default `base_url` for the docker client, which is the socket at  `unix:///var/run/docker/docker.sock`, I believe. 

Code reference:
https://github.com/docker/docker-py/blob/b27faa62e792c141a5d20c4acdd240fdac7d282f/docker/api/client.py#L79-L81

**Comment by miketheman** [comment]
@ryanjdillon can you provide more details as to the scenario?
Probably a code snippet, test scenario, configs and Paramus passes to pytest so I can try to reproduce?

**Comment by mattoberle** [comment]
I think this is the same issue from #70 / #71.
The combination of `--allow-unix-socket` and `--allow-hosts` does not work as expected.
Take this example test:

```py
import os
import socket
import tempfile

import pytest


def test_unix_connect():
    sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    with pytest.raises(FileNotFoundError):
        sock.connect('/tmp/socket.sock')


def test_inet_connect():
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    with pytest.raises(ConnectionRefusedError):
        sock.connect(('127.0.0.1', 8080))
 ```
 
 :green_circle:  Running pytest without the plugin will pass (expected):
 ```
$ pytest test.py
 ```
 
:green_circle:  Running pytest with `--disable-socket` will result in two failures (expected):
 ```
$ pytest --disable-socket test.py

FAILED test.py::test_unix_connect - pytest_socket.SocketBlockedError: A test tried to use socket.socket.
FAILED test.py::test_inet_connect - pytest_socket.SocketBlockedError: A test tried to use socket.socket.
```

:green_circle:  Running pytest with `--disable-socket --allow-unix-socket` will result in one failure for the TCP socket use (expected):
```
$ pytest --disable-socket --allow-unix-socket test.py

FAILED example_test.py::test_inet_connect - pytest_socket.SocketBlockedError: A test tried to use socket.socket.
```

:red_circle: Running pytest with `--allow-unix-socket --allow-hosts=127.0.0.1` will result in one failure for the Unix socket use (**unexpected**):
```
$ pytest --allow-unix-socket --allow-hosts=127.0.0.1

FAILED example_test.py::test_unix_connect - pytest_socket.SocketConnectBlockedError: A test tried to use socket.socket.connect() with host "None" (allowed: "127.0.0.1").
```

**Comment by miketheman** [comment]
@mattoberle Thanks for the details test case! I think I've discovered the logical error - and am working on figuring out the right approach to resolve.

TL,DR: there's a logical conflict between the config options, leading to failed outcomes. This is likely to change the 
flag combinations, so I'm treading carefully.
